// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
        defaultBrowser: "Firefox",
        handlers: [
                {
                	match: ({ url }) => url.host.endsWith("notion.so") || url.host.endsWith("whatsapp.com")|| url.host.endsWith("typst.app"),
                	browser: {
                		name: "Safari",
                	},
                },
                {
                        match: ({ url }) => url.host.endsWith("openai.com") || url.host.endsWith("chatgpt.com"),
                        browser: {
                                name: "/Applications/DuckDuckGo.app",
                                appType: "appPath",
                        },
                },
                // {
                // 	match: ({ url }) => url.host.endsWith("youtube.com"),
                // 	browser: {
                // 		name: "Firefox",
                // 	},
                // },
                // {
                // 	match: ({ url }) => url.host.endsWith("notion.so") || url.host.endsWith("whatsapp.com"),
                // 	browser: {
                // 		name: "Safari",
                // 	},
                // },
        ],
};
