// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
        defaultBrowser: "Firefox",
        handlers: [
                {
                	match: ({ url }) => url.host.endsWith("whatsapp.com"),
                	browser: {
                		name: "Safari",
                	},
                },
                {
                        match: ({ url }) => url.host.endsWith("openai.com"),
                        browser: {
                                name: "/Applications/DuckDuckGo.app",
                                appType: "appPath",
                        },
                },
        ],
};
