// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  handlers: [
		// {

		// 	match: ({ url }) => url.host.endsWith("google.com"),
		// 	browser: {
		// 		name: "/Applications/Firefox.app",
		// 		appType: "appPath",
		// 	},
		// },
		{
			match: ({ url }) => url.host.endsWith("openai.com"),
			browser: {
				name: "/Applications/DuckDuckGo.app",
				appType: "appPath",
			},
		},
	],
};
